[package]
name = "russimp"
version = "3.1.1"
authors = ["Jhonny Knaak de Vargas"]
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/jkvargas/russimp"
categories = ["rendering", "external-ffi-bindings", "game-engines", "multimedia"]
keywords = ["assimp", "3d", "blend", "3ds", "glTF"]
repository = "https://github.com/jkvargas/russimp"
description = "Assimp bindings for rust"
exclude = [ "*.bash", "/models" ]

[lib]
name = "russimp"
path = "src/lib.rs"

[dependencies]
russimp-sys = { git = "https://github.com/pema99/russimp-sys" }
num-derive = "0.4"
num-traits = "0.2.15"
num_enum = "0.6.1"
derivative = "2.2.0"
strum = "0.25"
strum_macros = "0.25"
mint = { version = "0.5.9", optional = true }

[features]
default = []
prebuilt = ["russimp-sys/prebuilt"]
static-link = ["russimp-sys/static-link"]
nozlib = ["russimp-sys/nozlib"]

[package.metadata.docs.rs]
features = ["prebuilt"]
